ls -l /home/runner/work/_temp/55081a65-60b1-4480-964d-45f63efd70ba.sh

name: Run GPT Request

on:
  push:
    branches:
      - main  # 実行をトリガーするブランチ

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # 使用するPythonのバージョンを指定

    - name: Install dependencies
      run: pip install requests  # requestsライブラリをインストール

    - name: Run Python script
      run:
        /home/runner/code/result.py  # 実行したいPythonスクリプトのパスを指定
      env:
        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: ${{ secrets.OPENAI_API_KEY }}  # シークレットからOpenAIのAPIキーを取得
